name: Build
on:
  pull_request:
  push:
    branches: [ ci, master, latest, 3.3-stable ]
  workflow_dispatch:
permissions:
  statuses: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure and build shared libraries
        run: |
          cmake -B build-null-shared -D GLFW_BUILD_WAYLAND=OFF -D GLFW_BUILD_X11=OFF -D BUILD_SHARED_LIBS=ON
          cmake -B build-x11-shared -D GLFW_BUILD_WAYLAND=OFF -D GLFW_BUILD_X11=ON -D BUILD_SHARED_LIBS=ON
          cmake -B build-wayland-shared -D GLFW_BUILD_WAYLAND=ON -D GLFW_BUILD_X11=OFF -D BUILD_SHARED_LIBS=ON
          cmake -B build-full-shared -D GLFW_BUILD_WAYLAND=ON -D BUILD_SHARED_LIBS=ON -D GLFW_BUILD_X11=ON
      - name: Build Wayland+X11 shared library
        run: cmake --build build-full-shared --parallel
      - name: Configure Win32 shared x64 library
        run: cmake -B build-win32-shared-x64 -G "Visual Studio 17 2022" -A x64 -D BUILD_SHARED_LIBS=ON
      - name: Build Win32 shared x64 library
        run: cmake --build build-win32-shared-x64 --parallel
